language: cpp

os: 
  - linux 
  - osx 

compiler:
  - clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
      - libopenmpi-dev
      - openmpi-bin
      - python-numpy
      - libblas-dev
      - liblapack-dev
  homebrew: 
    packages:
      - python
      - scons 
      - libxml2 

env:
  global:
    - PRECICE_ROOT="$TRAVIS_BUILD_DIR"
    - LOCAL_INSTALL="$HOME/local"
    - PETSC_ARCH=arch-linux2-c-debug
    - PETSC_DIR=$LOCAL_INSTALL/petsc
    - CPLUS_INCLUDE_PATH="$PETSC_DIR/include:$PETSC_DIR/$PETSC_ARCH/include:$LOCAL_INSTALL/include:$CPLUS_INCLUDE_PATH"
    - LD_LIBRARY_PATH="$PETSC_DIR/$PETSC_ARCH/lib:$LOCAL_INSTALL/lib:$LD_LIBRARY_PATH"
    - LIBRARY_PATH="$PETSC_DIR/$PETSC_ARCH/lib:$LOCAL_INSTALL/lib:$LIBRARY_PATH"
    - PYTHONPATH="$PETSC_DIR/$PETSC_ARCH/lib:/usr/lib/python2.7:/usr/lib/python2.7/dist-packages:/usr/lib/python2.7/plat-x86_64-linux-gnu"
    - EIGEN3_ROOT_DIR=${LOCAL_INSTALL}
    - BOOST_ROOT=${LOCAL_INSTALL}
    # required for boost linking on macOS
    - DYLD_LIBRARY_PATH={LOCAL_INSTALL}/stage/lib

  matrix:
    - TRAVIS_OS_NAME=osx MPI=off PETSC=off

cache:
  directories:
    - $LOCAL_INSTALL

before_install:
  - if [ $TRAVIS_OS_NAME = osx ]; then export PETSC_ARCH=arch-darwin-c-debug; else export PETSC_ARCH=PETSC_ARCH=arch-linux2-c-debug; fi
  - if [ $TRAVIS_OS_NAME = osx ]; then brew cask uninstall oclint; brew install open-mpi; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-6" && export CC="gcc-6"; fi
  - export OMPI_CXX=$CXX
  - if [ "$MPI" = "on" ]; then export CXX="mpicxx"; fi

install:
  - $TRAVIS_BUILD_DIR/tools/travis-install-dependencies.sh $LOCAL_INSTALL
  - export PATH=${LOCAL_INSTALL}/cmake/bin:${PATH}

before_script:
  - mkdir $TRAVIS_BUILD_DIR/build
  - mkdir $TRAVIS_BUILD_DIR/tests

script:
  - cd $TRAVIS_BUILD_DIR
  - cd build
  - cmake -DPETSC=$PETSC -DMPI=$MPI -DPYTHON=on -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX ..
  - cmake --build .
  - cd ../tests
  - if [ "$MPI" = "off" ]; then ../build/testprecice -x -r detailed > boost-test-output; fi
  - if [ "$MPI" = "on"  ]; then mpirun.openmpi -n 4 --output-filename boost-test-output  ../build/testprecice -r detailed; fi

after_failure:
  - cd $TRAVIS_BUILD_DIR
  - cat config.log
  - cat -n ./tests/boost-test-output*
