language: cpp
dist: trusty
sudo: false

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
      - libopenmpi-dev
      - openmpi-bin
      - python-numpy
      - libblas-dev
      - liblapack-dev
      - lcov

env:
  global:
    - HWLOC_HIDE_ERRORS=1
    - PRECICE_ROOT="$TRAVIS_BUILD_DIR"
    - LOCAL_INSTALL="$HOME/local"
    - PETSC_ARCH=arch-linux2-c-debug
    - PETSC_DIR=$LOCAL_INSTALL/petsc
    - CPLUS_INCLUDE_PATH="$PETSC_DIR/include:$PETSC_DIR/$PETSC_ARCH/include:$LOCAL_INSTALL/include:$CPLUS_INCLUDE_PATH"
    - LD_LIBRARY_PATH="$PETSC_DIR/$PETSC_ARCH/lib:$LOCAL_INSTALL/lib:$LD_LIBRARY_PATH"
    - LIBRARY_PATH="$PETSC_DIR/$PETSC_ARCH/lib:$LOCAL_INSTALL/lib:$LIBRARY_PATH"
    - PYTHONPATH="$PETSC_DIR/$PETSC_ARCH/lib:/usr/lib/python2.7:/usr/lib/python2.7/dist-packages:/usr/lib/python2.7/plat-x86_64-linux-gnu"
    - EIGEN3_ROOT_DIR=${LOCAL_INSTALL}/eigen3
    - BOOST_ROOT=${LOCAL_INSTALL}
    - BUILD_TYPE=CMAKE
    - CXXFLAGS="-Wall -Wextra -Wno-unused-parameter"

  matrix:
    - MPI=on PETSC=on
    - MPI=on PETSC=off
    - MPI=off PETSC=off

matrix:
  include:

      # testing builds on scons
    - if: type = cron or branch = master
      compiler: gcc
      env: BUILD_TYPE=SCONS MPI=on PETSC=on
    - if: type = cron or branch = master
      compiler: gcc
      env: BUILD_TYPE=SCONS MPI=on PETSC=off
    - if: type = cron or branch = master
      compiler: gcc
      env: BUILD_TYPE=SCONS MPI=off PETSC=off
    - if: type = cron or branch = master
      compiler: clang
      env: BUILD_TYPE=SCONS MPI=on PETSC=on
    - if: type = cron or branch = master
      compiler: clang
      env: BUILD_TYPE=SCONS MPI=on PETSC=off
    - if: type = cron or branch = master
      compiler: clang
      env: BUILD_TYPE=SCONS MPI=off PETSC=off

    # Test coverage
    - name: "Test Coverage"
      compiler: gcc
      script:
        - $TRAVIS_BUILD_DIR/tools/travis-coverage.sh
      after_success:
        - lcov --capture --directory "$TRAVIS_BUILD_DIR/build" --output-file coverage.info
        - lcov --remove coverage.info '/usr/*' "$LOCAL_INSTALL/*" --output-file coverage.info # filter system-files and local-dependencies
        - lcov --list coverage.info # debug info
        - bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"
    # Additional checks of code quality, etc
        - name: "Pull request check"
          if: type = pull_request
          include:
          script: bash tools/travis-pr-check.sh
          after_success:
          after_failure:


cache:
  ccache: true
  directories:
    - $LOCAL_INSTALL

before_install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-6" && export CC="gcc-6" && export CXXFLAGS="$CXXFLAGS -Wno-literal-suffix"; fi
  - export OMPI_CXX=$CXX
  - if [ "$MPI" = "on" ]; then export CXX="mpicxx"; fi

install:
  - $TRAVIS_BUILD_DIR/tools/travis-install-dependencies.sh $LOCAL_INSTALL
  - export PATH=${LOCAL_INSTALL}/cmake/bin:${LOCAL_INSTALL}/bin:${PATH}

before_script:
  - mkdir $TRAVIS_BUILD_DIR/tests

script:
  - $TRAVIS_BUILD_DIR/tools/travis-build-test.sh

after_failure:
  - cd $TRAVIS_BUILD_DIR
  - cat config.log
  - cat -n ./tests/boost-test-output*
